language: php
sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer install
  - mysql -e 'create database behavior_test;'

script:
  - phpunit

env:
  - DB_USER=travis DB_PASS= DB_NAME=behavior_test